### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by javydreamercsw** [tehapo/WizardsForVaadin#23]
While using 2.0.0 under Vaadin 7.7.7 it throws this error:

```
java.lang.NoSuchMethodError: com.vaadin.ui.Button.addClickListener(Lcom/vaadin/ui/Button$ClickListener;)Lcom/vaadin/shared/Registration;
	at org.vaadin.teemu.wizards.Wizard.initControlButtons(Wizard.java:151)
	at org.vaadin.teemu.wizards.Wizard.init(Wizard.java:130)
	at org.vaadin.teemu.wizards.Wizard.<init>(Wizard.java:119)
```
This is obviously a version mismatch, bt I was under the impression you were using the compatibility libraries.

**Comment by mschiffel** [comment]
Just spent over an hour on the same thing.

Got the exception
```
Severe:   java.lang.NoSuchMethodError: com.vaadin.ui.Button.addClickListener(Lcom/vaadin/ui/Button$ClickListener;)V
	at org.vaadin.teemu.wizards.Wizard.initControlButtons(Wizard.java:151)
	at org.vaadin.teemu.wizards.Wizard.init(Wizard.java:130)
	at org.vaadin.teemu.wizards.Wizard.<init>(Wizard.java:119)
```
when using Vaadin 8.0.* along with outdated WizardsForVaadin 1.1.1.

Problem disappeared after switching to WizardsForVaadin 2.0.1.
